version: "3.8"

services:
  fpm:
    build: docker/php
    container_name: fpm.content
    depends_on:
      - db
    volumes:
      - ./:/app
    networks:
      - content_network

  api:
    build: docker/nginx
    container_name: api.content
    depends_on:
      - fpm
    ports:
      - "8000:80"
    volumes:
      - ./:/app
      - ./docker/nginx/vhosts/rest.conf:/etc/nginx/sites-enabled/default
    networks:
      - content_network

  db:
    image: postgres:latest
    restart: always
    container_name: db.content
    ports:
      - "5433:5432"
    networks:
      - content_network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: blog_content

  es:
    build: docker/es
    container_name: elasticsearch.content
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - ./docker/data/es:/usr/share/elasticsearch/data
    networks:
      - content_network

networks:
  content_network:
    driver: bridge
    external: false

